# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

enableGitInfo = true

theme = "blowfish"
baseURL = "https://mopalinski.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-PEDMYR1V0K"

[pagination]
pagerSize = 20

[imaging]
anchor = 'Center'

[taxonomies]
author = "authors"
tag = "tags"
category = "categories"
series = "series"

[sitemap]
changefreq = 'always'
filename = 'sitemap.xml'
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]
