# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

mainSections = ["posts"]
# robots = ""

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "/img/pexels-controls-1853330_1920.webp"
# defaultFeaturedImage = "/img/featured.svg"
# defaultSocialImage = "/img/blowfish_banner.png"
hotlinkFeatureImage = false
# imagePosition = "50% 50%"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

#giteaDefaultServer = "https://git.fsfe.org"
#forgejoDefaultServer = "https://v11.next.forgejo.org"

fingerprintAlgorithm = "sha512" # Valid values are "sha512" (default), "sha384", "sha256"

showViews = false
showLikes = false

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  # homepageImage = "/img/iceland.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background
  disableHeroImageFilter = false # only used when layout equals hero

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = false
  showAuthorBottom = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/maciejopalinski/mopalinski.com/tree/master/content"
  editAppendPath = true
  seriesOpened = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showAuthorsBadges = true
  showWordCount = false
  showComments = true
  sharingLinks = false
  showSummary = true

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showSummary = false
  showTableOfContents = true
  showCards = true
  orderByWeight = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false
  constrainItemWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showTableOfContents = true
  cardView = true

[term]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showTableOfContents = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[firebase]
  # apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
  # authDomain = "blowfish-21fff.firebaseapp.com"
  # projectId = "blowfish-21fff"
  # storageBucket = "blowfish-21fff.appspot.com"
  # messagingSenderId = "60108104191"
  # appId = "1:60108104191:web:039842ebe1370698b487ca"
  # measurementId = "G-PEDMYR1V0K"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
  # identifier = "nunocoracao"
  # globalWidget = true
  # globalWidgetMessage = ""
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[rssnext]
  # feedId = ""
  # userId = ""

[advertisement]
  # adsense = ""